services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: microkafka-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - microkafka-net

  eureka:
    build:
      context: ./eureka
    container_name: microkafka-eureka
    ports:
      - "8761:8761"
    networks:
      - microkafka-net

  clients:
    build:
      context: ./clients
    container_name: microkafka-clients
    ports:
      - "8081:8081"
    environment:
      EUREKA_SERVER_URL: http://eureka:8761/eureka/
    depends_on:
      - eureka
    networks:
      - microkafka-net

  insurance-policy:
    build:
      context: ./insurance-policy
    container_name: microkafka-insurance-policy
    ports:
      - "8082:8082"
    environment:
      EUREKA_SERVER_URL: http://eureka:8761/eureka/
    depends_on:
      - eureka
    networks:
      - microkafka-net

  claims:
    build:
      context: ./claims
    container_name: microkafka-claims
    ports:
      - "8083:8083"
    environment:
      EUREKA_SERVER_URL: http://eureka:8761/eureka/
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - eureka
      - kafka
    networks:
      - microkafka-net

  notifications:
    build:
      context: ./notifications
    container_name: microkafka-notifications
    ports:
      - "8084:8084"
    environment:
      EUREKA_SERVER_URL: http://eureka:8761/eureka/
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - eureka
      - kafka
    networks:
      - microkafka-net

  gateway:
    build:
      context: ./gateway
    container_name: microkafka-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_SERVER_URL: http://eureka:8761/eureka/
    depends_on:
      - eureka
      - clients
      - insurance-policy
      - claims
      - notifications
    networks:
      - microkafka-net

networks:
  microkafka-net:
    driver: bridge
